version: '3.8'

services:
  web:
    # Build from the Dockerfile in the current directory
    build:
      context: .
      ssh:
        - default
    # Name the resulting image
    image: megamind
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent:ro
    # Set environment variables for the container
    environment:
      - SSH_AUTH_SOCK=/ssh-agent

