version: '3.8'

services:
  web:
    # Build from the Dockerfile in the current directory
    build:
      context: .
      ssh:
        - default
    # Name the resulting image
    image: megamind
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent:ro
    # Set environment variables for the container
    environment:
      - SSH_AUTH_SOCK=/ssh-agent

  nginx:
    # Use the latest stable nginx image
    image: nginx:latest
    # Map the host's port 80 to the container's port 80
    ports:
      - "8080:80"
    # Mount the nginx configuration file
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    # Ensure the 'web' service is started before the 'nginx' service
    depends_on:
      - web
